FROM maven:3.9.9-eclipse-temurin-21 AS build
ARG MODULE_NAME
WORKDIR /app
COPY . .
RUN mvn clean package -DskipTests -pl ${MODULE_NAME} -am

FROM eclipse-temurin:21-jre
ARG MODULE_NAME
WORKDIR /app
COPY --from=build /app/${MODULE_NAME}/target/*.jar app.jar
ENTRYPOINT ["java", "-jar", "app.jar"]
