
spring.datasource.url=jdbc:sqlserver://localhost;instanceName=SQLEXPRESS;databaseName=yt_tv;trustedServerCertificate=true;encrypt=false;
spring.datasource.username=sa
spring.datasource.password=sapassword
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=true

spring.application.name=yt-tv
spring.main.web-application-type=servlet
server.port=8080

spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.options.model=gemma3:4b
spring.ai.ollama.chat.options.temperature=0.2
spring.ai.ollama.embedding.model=nomic-embed-text:latest

spring.ai.vectorstore.chroma.client.host=http://localhost
spring.ai.vectorstore.chroma.client.port=8000
spring.ai.vectorstore.chroma.collection-name=yt_tv_videos
spring.ai.vectorstore.chroma.initialize-schema=true

youtube.api.key=${GOOGLE_API_KEY}

spring.main.allow-bean-definition-overriding=true