server.port=${PORT:8080}
spring.application.name=gateway-service
eureka.client.service-url.defaultZone=${EUREKA_SERVER:http://localhost:8761/eureka/}

# Routing
spring.cloud.gateway.routes[0].id=user-service
spring.cloud.gateway.routes[0].uri=lb://USER-SERVICE
spring.cloud.gateway.routes[0].predicates[0]=Path=/, /dashboard, /chat, /login/**, /register/**, /logout/**, /channels/**, /playlist/**, /playlists/**, /play/**, /css/**, /js/**, /api/users/**

spring.cloud.gateway.routes[1].id=content-service
spring.cloud.gateway.routes[1].uri=lb://CONTENT-SERVICE
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/channels/**, /api/videos/**

spring.cloud.gateway.routes[2].id=playlist-service
spring.cloud.gateway.routes[2].uri=lb://PLAYLIST-SERVICE
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/playlists/**, /api/watched/**

spring.cloud.gateway.routes[3].id=ai-service
spring.cloud.gateway.routes[3].uri=lb://AI-SERVICE
spring.cloud.gateway.routes[3].predicates[0]=Path=/api/ai/**

# Keep the original host for redirects behind the gateway
spring.cloud.gateway.default-filters[0]=PreserveHostHeader

server.forward-headers-strategy=framework